import { useState, useEffect } from 'react';
import { ExternalLink } from 'lucide-react';
import { profile } from '../../data/profile';
import DsaMap from './DsaMap';

// Fallback data — will be replaced by API/cached JSON
const fallbackData = {
  totalSolved: 268,
  easySolved: 120,
  mediumSolved: 130,
  hardSolved: 18,
  ranking: 450000,
  lastUpdated: '2024-12-01T00:00:00Z',
  source: 'fallback' as const
};

type LeetCodeStats = typeof fallbackData;

const LeetCode = () => {
  const [stats, setStats] = useState<LeetCodeStats>(fallbackData);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchStats = async () => {
      try {
        // Attempt to fetch from leetcode.json (generated by GitHub Action or manual update)
        const res = await fetch('/data/leetcode.json');
        if (res.ok) {
          const data = await res.json();
          setStats({ ...data, source: 'cached' as const });
        } else {
          setStats({ ...fallbackData, source: 'fallback' as const });
        }
      } catch {
        setStats({ ...fallbackData, source: 'fallback' as const });
      } finally {
        setLoading(false);
      }
    };
    fetchStats();
  }, []);

  return (
    <section id="algorithms" className="section container border-t">
      <div className="flex justify-between items-end mb-16 flex-wrap gap-4">
        <h2 className="font-mono text-tiny text-muted">ALGORITHMIC PRACTICE</h2>
        <a href={profile.leetcode} target="_blank" rel="noopener noreferrer" className="font-mono text-tiny hover:text-accent transition-colors flex items-center gap-2">
          [OPEN LEETCODE ↗] <ExternalLink size={12} />
        </a>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
        
        {/* Left Column: Stats + Sources */}
        <div className="lg:col-span-4 flex flex-col gap-8">
          
          {/* Stats Card */}
          <div className="bg-[#0a0a0a] border border-[#27272a] p-8">
            <h3 className="font-sans text-small text-white mb-6 border-b border-[#27272a] pb-4">LEETCODE STATS</h3>
            
            {loading ? (
              <div className="font-mono text-tiny text-dim animate-pulse">Syncing...</div>
            ) : (
              <div className="flex flex-col gap-4">
                <div className="flex justify-between items-baseline">
                  <span className="font-mono text-tiny text-muted">TOTAL SOLVED</span>
                  <span className="font-sans text-[2rem] font-bold text-accent leading-none">{stats.totalSolved}</span>
                </div>
                
                <div className="grid grid-cols-3 gap-2 mt-4 text-center">
                  <div className="bg-[#111] p-3 border border-[#27272a]">
                    <div className="font-mono text-[10px] text-green-400 mb-1">EASY</div>
                    <div className="font-sans font-bold text-white text-lg">{stats.easySolved}</div>
                  </div>
                  <div className="bg-[#111] p-3 border border-[#27272a]">
                    <div className="font-mono text-[10px] text-yellow-400 mb-1">MEDIUM</div>
                    <div className="font-sans font-bold text-white text-lg">{stats.mediumSolved}</div>
                  </div>
                  <div className="bg-[#111] p-3 border border-[#27272a]">
                    <div className="font-mono text-[10px] text-red-400 mb-1">HARD</div>
                    <div className="font-sans font-bold text-white text-lg">{stats.hardSolved}</div>
                  </div>
                </div>

                <div className="flex justify-between items-baseline mt-4 border-t border-[#27272a] pt-4">
                  <span className="font-mono text-tiny text-muted">GLOBAL RANK</span>
                  <span className="font-mono text-tiny text-white">{stats.ranking.toLocaleString()}</span>
                </div>
                
                <div className="font-mono text-[10px] text-dim mt-2 text-right">
                  {stats.source === 'fallback' ? (
                    <span className="text-yellow-600">USING FALLBACK DATA</span>
                  ) : (
                    <span>LAST SYNCED: {new Date(stats.lastUpdated).toLocaleDateString()}</span>
                  )}
                </div>
              </div>
            )}
          </div>

          {/* Learning Sources */}
          <div className="bg-[#0a0a0a] border border-[#27272a] p-8">
            <h3 className="font-sans text-small text-white mb-6 border-b border-[#27272a] pb-4">LEARNED THROUGH</h3>
            <div className="flex flex-col gap-4">
              <a href="https://takeuforward.org/dsa/strivers-a2z-sheet-learn-dsa-a-to-z" target="_blank" rel="noopener noreferrer" className="flex justify-between items-baseline group">
                <span className="font-mono text-tiny text-dim group-hover:text-white transition-colors">STRIVER A2Z</span>
                <span className="font-mono text-[10px] text-accent">474 problems ↗</span>
              </a>
              <a href="https://www.youtube.com/watch?v=Z2oxGj36vZk" target="_blank" rel="noopener noreferrer" className="flex justify-between items-baseline group">
                <span className="font-mono text-tiny text-dim group-hover:text-white transition-colors">LOVE BABBAR C++</span>
                <span className="font-mono text-[10px] text-accent">~10h ↗</span>
              </a>
              <div className="flex justify-between items-baseline">
                <span className="font-mono text-tiny text-dim">SELF PRACTICE</span>
                <span className="font-mono text-[10px] text-muted">CONTINUOUS</span>
              </div>
            </div>
          </div>

          <div className="font-serif text-small text-dim italic">
            "Optimization isn't just about speed — it's about understanding the underlying geometry of the problem."
          </div>
        </div>

        {/* Right Column: DSA Map */}
        <div className="lg:col-span-8">
          <DsaMap />
        </div>

      </div>
    </section>
  );
};

export default LeetCode;
